// .workspaces/frontend/src/uikits/ui8px/core/components/card/index.tsx
import React from 'react';
import { CardProps } from './interface';

/**
 * Card component with semantic class names
 * Follows the 8px design system
 */
export const Card: React.FC<CardProps> = ({
  variant = "default",
  elevation = "default",
  children,
  header,
  footer,
  className = "",
}) => {
  return (
    <div
      className={`card card-${variant} ${elevation !== "default" ? `card-${elevation}` : ""} ${className}`}
    >
      {header && (
        <div className={`card-header card-header-${variant}`}>
          {header}
        </div>
      )}
      <div className={`card-content card-content-${variant}`}>
        {children}
      </div>
      {footer && (
        <div className={`card-footer card-footer-${variant}`}>
          {footer}
        </div>
      )}
    </div>
  );
};

/**
 * Card Title component
 */
export const CardTitle: React.FC<{
  children: React.ReactNode;
  className?: string;
}> = ({ children, className = "" }) => {
  return (
    <h3 className={`card-title text-base font-medium ${className}`}>
      {children}
    </h3>
  );
};

/**
 * Card Description component
 */
export const CardDescription: React.FC<{
  children: React.ReactNode;
  className?: string;
}> = ({ children, className = "" }) => {
  return (
    <p className={`card-description text-sm text-muted-foreground ${className}`}>
      {children}
    </p>
  );
};

// .workspaces/frontend/src/components/ui/card/core/Card.svelte
<script lang="ts">
  import { type CardProps, cardVariants } from "../interface";
  import Badge from "../../badge/core/Badge.svelte";

  export let variant: CardProps["variant"] = "default";
  export let size: CardProps["size"] = "default";
  export let title: string = "";
  export let description: string = "";
  export let badges: { text: string; variant?: string }[] = [];

  // Generate semantic classes
  $: classes = `card card-${variant}${size !== "default" ? ` card-${size}` : ""}`;
</script>

<div class={classes}>
  {#if title}
    <div class="card-header">
      <h3 class="card-title">{title}</h3>
    </div>
  {/if}

  {#if badges.length > 0}
    <div class="card-badges">
      {#each badges as badge}
        <Badge variant={badge.variant}>{badge.text}</Badge>
      {/each}
    </div>
  {/if}

  {#if description}
    <div class="card-content">
      <p class="card-description">{description}</p>
    </div>
  {/if}

  <div class="card-footer">
    <slot name="footer" />
  </div>
</div>
