// .workspaces/frontend/src/uikits/infobiz/core/ui/button/index.tsx
import { type ButtonProps } from "./interface";

export function Button(props: ButtonProps & {
  href?: string;
  text?: string;
  dataPath?: string;
  children?: React.ReactNode;
  className?: string;
  onClick?: () => void;
}) {
  const {
    variant = "primary",
    size = "default",
    disabled,
    href,
    text,
    dataPath,
    children,
    className = "",
    onClick
  } = props;

  const classes = `button button-${variant} ${size !== "default" ? `button-${size}` : ""} ${className}`;

  if (href) {
    return (
      <a
        className={classes}
        href={href}
        data-path={dataPath}
      >
        {text || children}
      </a>
    );
  }

  return (
    <button
      className={classes}
      type="button"
      disabled={disabled}
      data-path={dataPath}
      onClick={onClick}
    >
      {text || children}
    </button>
  );
}

// .workspaces/frontend/src/components/ui/button/core/Button.svelte
<script lang="ts">
  import { type ButtonProps } from "../interface";

  export let variant: ButtonProps["variant"] = "primary";
  export let size: ButtonProps["size"] = "default";
  export let disabled = false;
  export let type: "button" | "submit" | "reset" = "button";

  $: classes = `button button-${variant} ${size !== "default" ? `button-${size}` : ""}`;
</script>

<button class={classes} {disabled} {type}>
  <slot></slot>
</button>
