// .workspaces/frontend/src/components/ui/button/core/Button.svelte
<script lang="ts">
  import { type ButtonProps } from "../interface";

  export let variant: ButtonProps["variant"] = "primary";
  export let size: ButtonProps["size"] = "default";
  export let disabled = false;
  export let type: "button" | "submit" | "reset" = "button";

  $: classes = `button button-${variant} ${size !== "default" ? `button-${size}` : ""}`;
</script>

<button class={classes} {disabled} {type}>
  <slot></slot>
</button>

// .workspaces/frontend/src/uikits/variants-ts/ui/button/index.tsx
import React from 'react';
import { ButtonProps } from './interface';

/**
 * Button component with semantic class names
 * Following the 8px design system
 */
export const Button: React.FC<ButtonProps & React.ButtonHTMLAttributes<HTMLButtonElement>> = ({
  variant = "primary",
  size = "default",
  disabled = false,
  className = "",
  children,
  ...props
}) => {
  return (
    <button
      className={`button button-${variant} ${size !== "default" ? `button-${size}` : ""} ${className}`}
      disabled={disabled}
      {...props}
    >
      {children}
    </button>
  );
};
